for pixel_r=5-half_windows_size:5+half_windows_size
            for pixel_c=5-half_windows_size:5+half_windows_size
                if or ( abs(pixel_r-interpolated_pixel_r)>half_windows_size,...
                        abs(pixel_c-interpolated_pixel_c)>half_windows_size)
                    continue
                end
        %if they are inside the boxs, sum up all cross-product GaussianWeigh*pixel_value         
                interpolated_image(row,column)=...
                    interpolated_image(row,column)...
                    +1/(2*pi()*sigma^2)*exp(-((pixel_r-interpolated_pixel_r).^2+(pixel_c-interpolated_pixel_c).^2)/(2*sigma^2))...
                    *LF(pixel_c,pixel_r, r+(5-pixel_r), c+(5-pixel_c), 1);
            end